<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USBLRMAKZARAK1" ignored="0" name="Tests4" tests="5" failures="3" timestamp="2021-09-16T13:16:28 IST" time="116.368" errors="0">
  <testcase name="check_item_details_in_cart" time="14.983" classname="testing.PurchaseTest"/>
  <testcase name="check_items_in_sub_category" time="3.087" classname="testing.PurchaseTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at pages.PurchasePage.validate_item(PurchasePage.java:164)
at testing.PurchaseTest.check_items_in_sub_category(PurchaseTest.java:75)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- check_items_in_sub_category -->
  <testcase name="check_total_price_of_items_in_cart" time="21.3" classname="testing.PurchaseTest">
    <failure type="java.lang.AssertionError" message="expected [75.00] but found [80.00]">
      <![CDATA[java.lang.AssertionError: expected [75.00] but found [80.00]
at pages.PurchasePage.check_total_subtotal(PurchasePage.java:184)
at testing.PurchaseTest.check_total_price_of_items_in_cart(PurchaseTest.java:136)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- check_total_price_of_items_in_cart -->
  <testcase name="purchase_without_delivery_address" time="20.043" classname="testing.PurchaseTest">
    <failure type="java.lang.AssertionError" message="expected [https://farmersapp-frontend-amxbp6pvia-as.a.run.app/user/order-status] but found [https://farmersapp-frontend-amxbp6pvia-as.a.run.app/user/checkout]">
      <![CDATA[java.lang.AssertionError: expected [https://farmersapp-frontend-amxbp6pvia-as.a.run.app/user/order-status] but found [https://farmersapp-frontend-amxbp6pvia-as.a.run.app/user/checkout]
at pages.PurchasePage.result_page(PurchasePage.java:170)
at testing.PurchaseTest.purchase_without_delivery_address(PurchaseTest.java:159)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- purchase_without_delivery_address -->
  <testcase name="start_purchasing" time="21.314" classname="testing.PurchaseTest"/>
</testsuite> <!-- Tests4 -->
